# MySQL Database Configuration
spring:
  datasourcex:
    url: jdbc:mysql://192.168.1.2:3306/kudori_local
    username: root
    password: Uqxomal1w
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      rewriteBatchedInserts: true   
  datasource:
    url: jdbc:postgresql://192.168.1.2:5432/public
    username: postgres
    password: jaimeduque
    driver-class-name: org.postgresql.Driver      
      
server:
  port : 8081
  